name: Docs
on:
  push:
    branches:
      - master
    paths:
      - '*.rst'
  pull_request:
    paths:
      - '*.rst'
jobs:
  pages:
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: git checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: pip install sphinx-design sphinxawesome-theme rstfmt
      - name: Check formatting
        run: rstfmt --check -w 80 *.rst
